### ISSUE TITLE
Fix bug: When click on school in admin, under schools tab, the app crashes

### ISSUE THREAD

**Issue by arouault** [MAPC/myschoolcommute2#102]

**Comment by arouault** [comment]
Bug school: http://staging.masaferoutessurvey.org/admin/schools/1889

OK school: http://staging.masaferoutessurvey.org/admin/districts/342

**Comment by allthesignals** [comment]
Might be for schools with survey responses

**Comment by allthesignals** [comment]
Uh oh, can't reproduce... @arouault can you check this again? Maybe some of the other issues I addressed fixed this? Maybe try a few times - could be some weird overloading issue.

**Comment by allthesignals** [comment]
Also the second link you posted is a district...
