### ISSUE TITLE
For street intersection markers, only allow one point on the map to show at a time

### ISSUE THREAD

**Issue by arouault** [MAPC/myschoolcommute2#106]
After selecting an intersection street, only allow one point on the map to show. Ensure "Drop point on map"  and "select point by intersection" are the same state.

**Comment by arouault** [comment]
![Screen Shot 2017-07-17 at 1.32.22 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54bee0371e908e0300842702/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f46b7191a379f111294f5d5d5ecc3c4a4356bcbbd671f3e57862804e0ee5d86f5f7cce6c12f8bc8a4ebc07b3208b4787b3bcdb4ed2f42f67b6d5db1063474f4dcbed5727a29f41c95df64be24c57a3153f62e77e2431.png)

When you go to use the intersecting streets feature in a survey, in addition to showing the intersection, it shows previous points you have selected. We would expect it to show the intersecting street once.

**Comment by mzagaja** [comment]
Going to ask if @ericyoungberg wants to check this issue out either on a consult or to submit a PR to the React component at https://github.com/MAPC/intersecting-streets-react. Otherwise, I have a bit of a learning curve to surmount before I think I can figure out what's happening here.

**Comment by mzagaja** [comment]
Talked to Eric and he said he'd also need a good amount of time to get up to speed. Will follow up to see if @allthesignals might be able to get this in during the week. If not then I'll teach myself some more react to see if I can figure it out before the end of the week, otherwise, will need to remove this from this release.
