### ISSUE TITLE
Stand up app on production environment

### ISSUE THREAD

**Issue by allthesignals** [MAPC/myschoolcommute2#108]
- [x] @mzagaja EC2 setup, Capistrano
 - [ ] R environment
 - [x] Permissions
 - [ ] Other

**Comment by mzagaja** [comment]
Merged develop into master and set it up to run on the Amazon lightsail server we have right now (dyee.mapc.org) since live.mapc.org is currently "hogged" by data common. I also did a generic R setup. Just needs the data export and to be tested.

**Comment by mzagaja** [comment]
Going to use live.mapc.org instead since dyee.mapc.org will be retired soon.
