### ISSUE TITLE
In Districts Tab, make sure "survey response" tally doesn't include incomplete surveys

### ISSUE THREAD

**Issue by arouault** [MAPC/myschoolcommute2#111]
Surveys without a start or end date are currently counting toward a "survey response" even though they are "drafts" of a survey that never went live. Remove them from the count of "survey responses" 
![screen shot 2017-07-17 at 1 49 36 pm](https://user-images.githubusercontent.com/1305629/28281973-cc23b326-6af6-11e7-9764-b7058451f004.png)

**Comment by mzagaja** [comment]
Given that the only thing needed for a survey to activate is to give it a begin and end date, would it make sense to simply prevent people from creating "draft" surveys by requiring both a begin and end date?

**Comment by arouault** [comment]
Still seeing old survey responses that lack start and end dates in the tally. Can you solve this by 1) deleting those records or 2) not include them in survey response total ? 

For examples, the tally here is 2 survey responses but both of them are not real survey responses, just false starts 

![screen shot 2017-08-18 at 10 12 25 am](https://user-images.githubusercontent.com/1305629/29462567-d1164fae-83fd-11e7-8230-3517c0319422.png)
