### ISSUE TITLE
Display Intersection Point on the Map

### ISSUE THREAD

**Issue by mzagaja** [MAPC/myschoolcommute2#116]
If they choose an intersection they should see what point we're using for the intersection on the map.

**Comment by allthesignals** [comment]
I think this is me, @mzagaja - yes?

**Comment by mzagaja** [comment]
@allthesignals yes sir!

**Comment by allthesignals** [comment]
@mzagaja so, looking at this issue - they _can_ see which point is going to be used. It's never not there, it's just not indicated. How do you want me to indicate this? Do I fade out the other points by adjusting opacity? Do I center the map on the selected point? Does it turn into some other icon? I think I will make the others disappear if they choose one.

**Comment by mzagaja** [comment]
Going to ask @arouault to weigh in on this because on the latest commit in develop it seems to show a point to me:
![screen shot 2017-08-23 at 10 32 55 am](https://user-images.githubusercontent.com/565647/29621360-81045296-87ee-11e7-9c4f-314416a9244d.png)

So not sure if it was supposed to be styled differently or if it maybe wasn't working on staging?

**Comment by allthesignals** [comment]
This is addressed by 0be4c816da2a1868f950bcbdefb48e97ce8c19ea. @mzagaja, please close if this works. I didn't hear any specific feedback about how this show happen, but my solution simply renders the selected point at full opacity, and the others at half.

**Comment by mzagaja** [comment]
So I totally didn't understand what you were getting at with the opacity thing until I pulled down the fix, but it looks great to me. I #approve.
