### ISSUE TITLE
Import Users from Old Site

### ISSUE THREAD

**Issue by mzagaja** [MAPC/myschoolcommute2#121]
Users need to be imported from the old site. Need to work with the client to figure out how they should be notified if at all.

**Comment by mzagaja** [comment]
Implemented in 863a065999f21917072fd455d595da1f74020109 and waiting for users to confirm it works.

**Comment by arouault** [comment]
Sounds like Erin couldn't login when she tried. @mzagaja

**Comment by mzagaja** [comment]
Logins from old site work but need to make sure to import administrative privileges

**Comment by mzagaja** [comment]
Confirmed admin privilege column is being imported so this should be set.
