### ISSUE TITLE
Batch Entry Not Associating Survey Responses with Surveys

### ISSUE THREAD

**Issue by mzagaja** [MAPC/myschoolcommute2#123]
I thought I would try entering the West Barnstable Elementary surveys on the new site as the map and drop down for street options does work.. It seems as if the staging site doesn’t quite know how to attach the batch entry surveys to a survey instance yet. I entered three to see what would happen. The first two let me submit the data but the number of survey logged responses stayed at 0. The third attempt gave me an error message. I know the looping of the batch entry is still being worked out.  I’m glad we have some actual paper surveys to enter in order to test this out. Thanks for working through all of the glitches.

**Comment by allthesignals** [comment]
@mzagaja was it clear why responses weren't being associated? You have to select a survey from the dropdown. Do you need anymore help from me on this?

**Comment by mzagaja** [comment]
@allthesignals yep this one I should be able to fix with the label. Easy peasy.

**Comment by allthesignals** [comment]
@mzagaja great - I'm going to un-assign myself to keep organized. Thanks!
