### ISSUE TITLE
West Barnstable Elementary Not Displaying Correctly

### ISSUE THREAD

**Issue by mzagaja** [MAPC/myschoolcommute2#124]
I know we are chatting later but it looks like something did not work quite right in adding West Barnstable Elementary School. It does not seem to have a walkshed and the associated drop down list of streets does not work. I imagine if it’s pulled over to the new site as is, then it won’t work there either. Can you  please take a look at this and let us know how you fixed it? Thanks.

**Comment by mzagaja** [comment]
Further research has revealed that the export works ok but is not including the walk sheds. The geometry of all sheds beside shed_05 do not get generated and carry over. The JSON has the appropriate geometry and walkshed but it does not display in the leaflet map.

**Comment by allthesignals** [comment]
I addressed some of this here: c58a7c258674075019cd77b2b59e099052bea109. Some schools sheds weren't appearing because of the data wasn't being validated correctly.
