### ISSUE TITLE
Javascript Errors on Staging (but not Dev)

### ISSUE THREAD

**Issue by mzagaja** [MAPC/myschoolcommute2#133]
In the latest deploy to staging I'm getting Javascript errors and not seeing the date picker or react/js elements appear. Weirdly it works fine on my local machine.

The error I get on the server on the regular survey entry page is:

![screen shot 2017-08-22 at 4 35 55 pm](https://user-images.githubusercontent.com/565647/29586259-0afba680-8758-11e7-9ede-654269d60129.png)

I don't get an error when the date picker fails.

**Comment by allthesignals** [comment]
Sorry, un-assigning myself - I didn't commit this code

**Comment by mzagaja** [comment]
Solutions tried so far:

1. Reboot staging server
2. Restart nginx
3. Rerun `cap staging deploy`

@allthesignals In the realm of code you did commit I'm getting an error in intersectingstreets.js.min.

![screen shot 2017-08-22 at 4 46 40 pm](https://user-images.githubusercontent.com/565647/29586681-8f0a9bec-8759-11e7-87c2-38ca58287f83.png)

At this point, I'm not sure if it's a javascript issue or if it's a server issue or something in between so I'm going to try and triangulate this tomorrow but may need an "assist" once I've gotten a better sense of it.

**Comment by allthesignals** [comment]
`window.__` is the helper function for translating text.

**Comment by allthesignals** [comment]
See https://github.com/webhippie/gettext_i18n_rails_js

**Comment by mzagaja** [comment]
Ah ok, thanks for the tip. I am currently attempting to git bisect it to see if I can find the commit it was introduced in. My hunch right now is maybe an interaction between my date picker and your stuff, but could also be a rails asset pipeline problem too. If it's not those things then might have been a change to the javascript on your end. But since it works locally I'm not completely convinced it's that.

**Comment by mzagaja** [comment]
Ok so just deployed hash 5b7e86a5b6114b7b788e6fee03dcb7912c9a4135 and that is working fine, going to work my way forward until I find the offending commit.

**Comment by mzagaja** [comment]
Last deploy is 5b7e86a5b6114b7b788e6fee03dcb7912c9a4135 where it is broken, so zeroing in slowly.

**Comment by mzagaja** [comment]
And the winner is dfe564c1a1306e7960f42a8d73be00e2a015446c so this is definitely something I did.

**Comment by mzagaja** [comment]
Commenting out https://github.com/MAPC/myschoolcommute2/blob/dfe564c1a1306e7960f42a8d73be00e2a015446c/app/assets/javascripts/new_school.js resolves this, but we lose the school picker functionality. Going to try to figure out how to get this to play nice.
