### ISSUE TITLE
PDF Reports not generating (Mission Critical)

### ISSUE THREAD

**Issue by arouault** [MAPC/myschoolcommute2#145]
PDF Reports not generating for schools with old survey data after deploying latest build of the site. This is an issue that came up a few weeks ago here: https://github.com/MAPC/myschoolcommute2/issues/142

And is now back!

**Comment by ericyoungberg** [comment]
This issue has been fixed and I stated the solution in the Slack channel but I'll post here for documentation's sake:

> In order to get the reports generating, the server needed to have 
> ```bash
> apt-get install -y texlive texlive-science texinfo texlive-binaries texlive-latex-extra
> ```
> Additionally, I had to install R along with all of the R packages from CRAN that are listed in the 
> _compile.R_ file. I had to edit the _/etc/environment_ file to set the `$DATABASE_URL` global 
> environment variable to properly communicate with __db.live.mapc.org__
