### ISSUE TITLE
Carto presence in School model

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/myschoolcommute2#172]
Carto is currently written into the codebase in a few locations. We should check these locations for how/if they function and proceed to remove Carto. 

- https://github.com/MAPC/myschoolcommute2/blob/develop/app/models/school.rb#L85
- https://github.com/MAPC/myschoolcommute2/blob/develop/app/views/_intersection.js.erb (looks like this whole file could be removed)

**Comment by mzagaja** [comment]
Superseded by #204.
