### ISSUE TITLE
Administrate is broken

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/myschoolcommute2#192]
We've had a couple of issues in other areas of the site regarding administrate's implementation (like password resets). We should evaluate the broken areas of administrate. 

The possible best path to take is to do a full reinstall of administrate. We have upgraded ruby/rails which has caused administrate to fail in certain areas.

**Comment by mzagaja** [comment]
Closing this as it lacks sufficient detail to reproduce and does not seem to be broken in current build.
