### ISSUE TITLE
Fix typo in Report page 1 footnote

### ISSUE THREAD

**Issue by TimReardon** [MAPC/myschoolcommute2#199]
Footnote about enrollment data on page 1 should be one sentence with three elements in the series, separated by commas, not two sentences. Correct syntax should read: 

"Survey data discrepancies may exist in cases where more than one survey was submitted per student, current year enrollment is not currently available, or school enrollment has increase since reported to ESE on October 1st."

**Comment by ericyoungberg** [comment]
This is my last MAPC issue. Let it be written in the books.
