### ISSUE TITLE
Change Logo

### ISSUE THREAD

**Issue by theryankelly** [MAPC/myschoolcommute2#201]
Update the logo on Footer. Confirm changes match changes made on the report.  Logo attached
![SRTS Logo RGB 1575x505](https://user-images.githubusercontent.com/2421382/57708493-72a1dc80-7637-11e9-9ae7-9fe120ff43d1.png)

**Comment by atomtay** [comment]
Resolved in commits [770971](https://github.com/MAPC/myschoolcommute2/commit/7709711a2ca80142ce2a6e754875b4a4a3a6473a) (report) and [dfb48c](https://github.com/MAPC/myschoolcommute2/commit/dfb48cee7b6068de15e73e45fae5b6909764a221) (site footer)
