### ISSUE TITLE
Unclear what attributes are necessary to add a school

### ISSUE THREAD

**Issue by atomtay** [MAPC/myschoolcommute2#207]
It does not appear that all fields are necessary to create a school from the admin console (though I haven't tested to see how excluding fields impacts other groups like Districts and Survey Responses). At a minimum, the user needs to input the DOE Org Code and the School Location. However, there is no cue that indicates these fields are required.

Excluding the location provides this error:
```
undefined method `x' for nil:NilClass

```
with a particular focus on this line from `app/models/school.rb`:
```
 point = RGeo::Cartesian.factory(srid: 4326, proj4: '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs').point(self.geometry.x, self.geometry.y)
```

Excluding the DOE code provides this error:

```
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "survey_school_schid_key" DETAIL: Key (schid)=() already exists. : INSERT INTO "schools" ("name", "schid", "address", "town_mail", "town", "state", "zip", "principal", "phone", "fax", "grades", "schl_type", "survey_incentive", "survey_active", "geometry") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING "id"
```

It looks like DOE Org Code maps to `schid` in the database, though there is another element (simply called `id`) that is automatically generated.

Should we add anything that indicates the need for particular fields, or should the use case be that all are necessary (and so an error should be thrown if anything is missing)?

**Comment by mzagaja** [comment]
It probably would make sense to do this since the database is enforcing the constraint, or in the alternative we can decide not to make that column unique. In this case I think its probably good to just add the validation to the school model so that it propagates to the admin console in relation to `schid`.

I think requiring location is ok too since we do need it.
