### ISSUE TITLE
Styling (basic)

### ISSUE THREAD

**Issue by allthesignals** [MAPC/myschoolcommute2#25]
Hex codes
 - [x] Create color scheme

**Comment by arouault** [comment]
Fonts: 
Body: Franklin Gothic URW Book
Header: Franklin Gothic URW Medium

Webkit embed code:  <script src="https://use.typekit.net/fxq4ijr.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>

class for CSS: .tk-franklin-gothic-urw

hex for header div: #3399CC
hex for body text: #FFFFFF

![myschoolcommute-01](https://cloud.githubusercontent.com/assets/1305629/26646549/0bcf0366-460a-11e7-9815-a970a765ce0b.png)

**Comment by arouault** [comment]
Need to implement this font

**Comment by arouault** [comment]
Also: please Align subnavigation (once logged in) to Main Navigation
