### ISSUE TITLE
Build new administrative interface in Rails 

### ISSUE THREAD

**Issue by arouault** [MAPC/myschoolcommute2#3]
Take the full functionality of the Django admin interface and rebuild in rails 

- assign and delete users
- view all reports (by district or school)
- view active/inactive surveys, number of surveys
- Create survey
- assign data range to surveys 
- add additional survey fields (more children)
- PDF survey report generation
- View and manage survey results and reports
- View walkshed on interactive map
- Translate online answers in other languages to english
- Export all results as CSV
- District Resources

**Comment by allthesignals** [comment]
The current site splits this between a canned administrator view and a district-level manager view:

![Screen Shot 2017-05-23 at 2.13.55 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/83944056-281c-4595-becf-7b8d82ba8fed/Screen+Shot+2017-05-23+at+2.13.55+PM.png)
![Screen Shot 2017-05-23 at 2.09.41 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/83944056-281c-4595-becf-7b8d82ba8fed/Screen+Shot+2017-05-23+at+2.09.41+PM.png)

The district show view should do a lot of the same, but the administrator view for managing users should be handled with a Rails canned administrator gem. 

Administrate Gem:
 - [ ] assign and delete users

Custom District Show View:
 - [ ] view all reports (by district or school)
 - [ ] view active/inactive surveys, number of surveys
 - [ ] Create survey
 - [ ] assign data range to surveys
 - [ ] Export all results as CSV
 - [ ] PDF survey report generation
 - [ ] View and manage survey results and reports
 - [ ] View walkshed on interactive map

Survey view:
 - [x] add additional survey fields (more children) - taken care of in #15 (@arouault can you confirm)

App-wide menu link/page (@arouault can you confirm this separation): 
 - [ ] Translate online answers in other languages to english
 - [ ] District Resources

**Comment by allthesignals** [comment]
Some database queries in the school view:

("surveys" = "survey_responses")

- [ ] Number of surveys in the past 24 hours
- [ ] Number of surveys in the past week
- [ ] Number of surveys total
- [ ] Is there an active survey?

**Comment by allthesignals** [comment]
needs #24

**Comment by allthesignals** [comment]
Needs #10
