### ISSUE TITLE
Users auth and user management

### ISSUE THREAD

**Issue by allthesignals** [MAPC/myschoolcommute2#30]
#29 begins the buildout of this larger view, but this is specific the ability to manage user roles (which include statically-defined permissions). 

Users want to:
 - [x] Make a user a superadmin (can access Administrate admin panel)
 - [x] Make a user a school admin (can enter data)

**Comment by allthesignals** [comment]
@arouault can you comment on this? Did you have some notes about this?

**Comment by arouault** [comment]
will provide some thoughts tomorrow!

**Comment by arouault** [comment]
Sorry for the very delayed reply. Curious what kind of feedback you're looking for? Visual? Design? Information architecture? 

I see you implemented login which looks good so far. I created an account but then must be given permissions by the super user. Curious if you have implemented the "super user" view yet? If not, I can provide some thoughts.  Can we discuss in person?
