### ISSUE TITLE
Add logos to Footer 

### ISSUE THREAD

**Issue by arouault** [MAPC/myschoolcommute2#40]
Please add these logos to the footer and constrain to the same width. @allthesignals let me know if you need me to resize before you implement or if you can in the browser.

![image](https://cloud.githubusercontent.com/assets/1305629/26646714/a21bb53a-460a-11e7-977e-5381f05c45df.png)
![image](https://cloud.githubusercontent.com/assets/1305629/26646719/adf37e88-460a-11e7-8663-ebda17b4e446.png)
![image](https://cloud.githubusercontent.com/assets/1305629/26646736/c6b6ad46-460a-11e7-8ccf-2e6b4c93aa3d.png)

**Comment by allthesignals** [comment]
Old site: 
![Screen Shot 2017-06-16 at 9.49.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455f56b7191a371f116224f5b595edd3c4a4356bcbbd671f3e57862804e0ee5d86f5f7cce6c12f8bc8a4ebc07b3208b4787b3bcdb4ed2f42f67b6d5db1063474f4dcbed5727a29a48cd5bfc4ae54452a2113763e671347b438653.png)

Horizontal placement of footer logos.

**Comment by arouault** [comment]
@arouault swap out for svgs
