### ISSUE TITLE
Superadmin UI for Creating/Alerting New Users and Assigning Permissions; Deleting any user

### ISSUE THREAD

**Issue by arouault** [MAPC/myschoolcommute2#42]

**Comment by arouault** [comment]
Create superadmin UI that allows super admin to: 

- [ ] create new users (email and password)
- [ ] send those new users an email with their credentials 
- [ ] delete users
- [ ] assign users permission (district or school)

**Comment by allthesignals** [comment]
@mzagaja question on infrastructure: do you know of an existing solution for doing Rails mailers in phusion passenger? Is this a difficult task?

**Comment by mzagaja** [comment]
It's not the worst. Check out https://github.com/MAPC/youth-match-v2/commit/36d04e6aa6b8079d9208151d01ceddbaaae71bdb for an example of setting up Mailgun with Youth Match and then https://github.com/codeforboston/cambridge_energy_app/commit/a85cde7f68208de32bdfe42f384d917b16616a1b for Devise with mailer templates. The instructions for generating the views are [here](http://devise.plataformatec.com.br/#configuring-views).
