### ISSUE TITLE
Deploy app to AWS EC2 instance

### ISSUE THREAD

**Issue by allthesignals** [MAPC/myschoolcommute2#46]
Continuing from #24, this issue has blossomed into its own issue. Here's the original comment:

[Here](https://mapc.slack.com/archives/C17CVQB3N/p1496366929091749) @mzagaja suggests deploying to a custom Linux server:

> Honestly my general sense is you’re better off deploying to a vanilla Linux server for something like this

This way we can save a lot of time running the R script (which has many heavy dependencies in addition to R's own packages).

**Comment by mzagaja** [comment]
I'm going to deploy this to the Amazon LightSail instance I set up for YouthMatch for now. And then setup Capistrano. Things to do to get this working:

1. Create appropriate username/password for the application on dyee.mapc.org
2. This project needs a domain or sub-domain to be setup from Ty.
3. Load Capistrano into the project repo
4. Setup a staging app instance as well

**Comment by mzagaja** [comment]
Sent note to ITHelp to point staging.masaferoutessurvey.org to my Amazon LightSail staging server so we can get an environment setup for the develop branch/staging. After I successfully do that there, I'll do the live version after.

**Comment by mzagaja** [comment]
Almost done but currently blocked from setting up the staging database by the following error:

PG::InsufficientPrivilege: ERROR:  permission denied to create extension "pgrouting"
HINT:  Must be superuser to create this extension.
: CREATE EXTENSION IF NOT EXISTS "pgrouting"

I need either a postgres user with superuser privileges or alternatively someone with a superuser privileges person to add the pg_routing extension to the myschoolcommute2_staging database. @allthesignals

**Comment by allthesignals** [comment]
@mzagaja 

`ssh` in and `sudo su postgres` which setup the correct user.

**Comment by mzagaja** [comment]
I don't have SSH access/credentials to db.live.mapc.org.

**Comment by mzagaja** [comment]
Ok this is now live for the staging site: http://staging.masaferoutessurvey.org/
