### ISSUE TITLE
Restore/debug the "Add New District" button

### ISSUE THREAD

**Issue by arouault** [MAPC/myschoolcommute2#64]
Create a way to add new school districts

**Comment by allthesignals** [comment]
Administrate is loading every related school record to populate the New District dropdown menu. 

`...INNER JOIN SELECT * FROM SCHOOLS` <- performance bottleneck!

Matt: we should patch administrate

[b] - Alternative solution (workaround): remove schools selection dropdown from New District, allow user to associate the schools by going to them individually.[/b] <- This is the solution path for now. 

 - Refactoring option: abstract walkshed columns into another relational table.
