### ISSUE TITLE
Final Data Migration

### ISSUE THREAD

**Issue by allthesignals** [MAPC/myschoolcommute2#74]
The user data from the old site needs to be pulled in as well as the most updated surveys/survey_responses (the program has run a few surveys since the last data import). 

- [ ] Legacy user data
- [x] Update most recent surveys/survey responses data

**Comment by mzagaja** [comment]
?

**Comment by allthesignals** [comment]
Woops, sorry - updated description! @mzagaja

**Comment by mzagaja** [comment]
After burning way too much time on this, I have ascertained that there are only a small number of survey responses that also happen to be orphaned. I developed the following pattern to get the data from the mysc database on our django server:

```
# Export Tables from mysc database
# COPY schools TO '/tmp/schools.csv' DELIMITER ',' CSV HEADER;
# COPY survey_set TO '/tmp/survey_set.csv' DELIMITER ',' CSV HEADER;
# COPY schools (id,schid) TO '/tmp/schools_join.csv' DELIMITER ',' CSV HEADER;
# Download survey_child_survey from the MYSC website link on the bottom


# Add schid to survey_set data
csvsql --query "SELECT survey_set.*, schools_join.schid FROM survey_set INNER JOIN schools_join ON survey_set.school_id = schools_join.id;" survey_set.csv schools_join.csv > survey_set_schools.csv

csvsql --query "SELECT survey_child_survey.id, survey_child_survey.grade, survey_child_survey.to_school, survey_child_survey.dropoff, survey_child_survey.pickup, survey_child_survey.school_id, survey_child_survey.street, survey_child_survey.cross_st, survey_child_survey.nr_vehicles, survey_child_survey.nr_licenses, survey_child_survey.distance, survey_child_survey.created, survey_child_survey.modified, survey_child_survey.st_astext, survey_child_survey.schid, survey_set_schools.id AS survey_id FROM survey_child_survey LEFT OUTER JOIN survey_set_schools ON survey_child_survey.schid = survey_set_schools.schid AND survey_child_survey.created BETWEEN survey_set_schools.begin and survey_set_schools.end;" survey_child_survey.csv survey_set_schools.csv > survey_responses_merged.csv
```
The number of rows that appear in survey_responses_merged.csv matches that of the committed survey_responses.csv dump. However the above code does not return the same survey values as the committed survey_responses.csv

**Comment by mzagaja** [comment]
Email from Erin:

> Hi Matt,
> The Barnstable Public Schools-surveyed from June 2-June 16th
>  
> Barnstable High
> Barnstable Horace Mann Charter School
> Centerville Elementary
> Hyannis West Elementary
> West Barnstable Elementary
> West Villages Elementary School
>  
>  
> Missing Barnstable Schools-not on either site:We had emailed Alicia and Matt and I thought they were going to work to add these school as all of these schools survey during the June 2-16 timeframe as well.
> Barnstable Intermediate School
> Barnstable United Elementary School
> Enoch Cobb Early Learning
>  
> Thanks for taking care of cleaning of this data before pulling the data.
> ~Erin

Based on this and the phone call I learned there was a batch entry of survey data in July but the survey occurred in June. So the "created" date seems like a more likely correct candidate for matching surveys to data.

**Comment by mzagaja** [comment]
Further digging has revealed a few things:

1. Surveys should generally be joined with the survey responses using the "created" date between the survey start and end dates. Sometimes there have been data entry errors leading to orphaned surveys.

2. One of the most recent survey entries was missing a relevant school survey.

3. The survey "end dates" are set to midnight on the date they ended when they really should have been set to 11:59:59 and therefore when making queries they have to be incremented by one day.

Noting these changes reduces orphaned surveys to 832.

The new csvkit query to create the final export file is:

```
# Export Tables from mysc database
# COPY survey_set TO '/tmp/survey_set.csv' DELIMITER ',' CSV HEADER;
# COPY survey_schools (id,schid,name,town) TO '/tmp/schools_name_town_join.csv' DELIMITER ',' CSV HEADER;
# Download survey_child_survey from the MYSC website link on the bottom


# Add schid to survey_set data
csvsql --query "SELECT survey_set.*, schools_name_town_join.schid FROM survey_set INNER JOIN schools_name_town_join ON survey_set.school_id = schools_name_town_join.id;" survey_set.csv schools_name_town_join.csv > survey_set_schools.csv

csvsql --query "SELECT survey_child_survey.id, survey_child_survey.grade, survey_child_survey.to_school, survey_child_survey.dropoff, survey_child_survey.pickup, survey_child_survey.school_id, survey_child_survey.street, survey_child_survey.cross_st, survey_child_survey.nr_vehicles, survey_child_survey.nr_licenses, survey_child_survey.distance, survey_child_survey.created, survey_child_survey.modified, survey_child_survey.st_astext, survey_child_survey.schid, survey_set_schools.id AS survey_id, date(survey_set_schools.end, '+1 day') AS survey_end FROM survey_child_survey LEFT OUTER JOIN survey_set_schools ON survey_child_survey.schid = survey_set_schools.schid AND survey_child_survey.created BETWEEN survey_set_schools.begin and survey_end;" survey_child_survey.csv survey_set_schools.csv > survey_responses_merged.csv
```
